### ISSUE TITLE
Access denied when trying to create a new group

### ISSUE THREAD

**Issue by netdrag** [amooma/GS5#35] opened 2012-12-28 00:19 UTC
I am getting:

Access denied! Please ask your admin to grant you the necessary rights.

when I try to create a new Group. 

I log into the webinterface and go to the url: 
http://localhost:8080/tenants/2/user_groups/new

its localhost because I am using ssh forwarding. But thats not the problem cause it also happens on another machine in the network where gemeinschaft is installed.

Then I insert the name an click submit and get the screen with the error message. 
![Bildschirmfoto](https://f.cloud.github.com/assets/1911688/33389/d2377492-5083-11e2-9704-6d2919b970ae.png)

As you see, the url is jumping to localhost:8080

I tried that on 2 fresh installations with the same result

**Comment by wintermeyer** [comment] 2012-12-28 09:14
I was not able to reproduce this error with the Live CD.

**Comment by TobiasW** [comment] 2012-12-30 11:54
I am also not able to create a new group. Tested with 5.0 and 5.0.1 with Live CD and installation.
Or is there anything special to keep in mind by creating a new group, except being admin?

**Comment by wintermeyer** [comment] 2012-12-30 12:00
Which URL do you use to create a new user_group? Please submit a screenshot of the new form and the next page (the one with the error).

**Comment by TobiasW** [comment] 2012-12-30 12:09
I used this URL: http://192.168.100.55/tenants/2/user_groups/new

![new_form](https://f.cloud.github.com/assets/407146/35798/8b6d0692-5279-11e2-85d7-bc7963586ebe.jpg)

![error](https://f.cloud.github.com/assets/407146/35799/aa3d46ea-5279-11e2-914d-316a57bf0839.jpg)

**Comment by wintermeyer** [comment] 2012-12-30 14:51
Fixed by caf624f11f7de44289b3c994fc72cc5e32ed799e

**Closed as completed by wintermeyer** 2012-12-30 14:51 UTC
Labels: Bug

**Comment by TobiasW** [comment] 2012-12-30 15:48
Sorry to keep bothering you with this, but I think you should change the update and destroy method in the same way.

**Comment by wintermeyer** [comment] 2012-12-30 16:12
Don't be sorry! Thanks for finding the bug and giving a good bug report. 
Fixed by cc2a6de28e676b5afb73f3fafb5b417301927cc9
