### ISSUE TITLE
Hot desking does not work as expected

### ISSUE THREAD

**Issue by duebel-** [amooma/GS5#162] opened 2013-02-05 16:43 UTC
URL which triggered the bugreport is: /tenants/2/users/2
GS5 buildname: 1302051015 (5.1-develop)

User is logged in phone A:

SIP-Accounts
Online  Caller Name     Telefonnummern  Telefon
    Frank   +XXXX, 123  00:04:13:48:31:BB (Snom 821) (10.0.0.18)    Anzeigen Bearbeiten Löschen

Telefone
MAC-Adresse     Modell  Hot-Desk fähig     IP-Adresse
00:04:13:48:31:BB   Snom 821    Ja  10.0.0.18   Anzeigen Bearbeiten Löschen

User logs into phone B:
-> phone A restarts, phone B does not show logged in user, phone A shows user as logged in

SIP-Accounts
Online  Caller Name     Telefonnummern  Telefon
    Frank   +XXXX, 123  00:04:13:48:31:BB (Snom 821) (10.0.0.18) 00:04:13:48:2D:A8 (Snom 821) (10.0.0.11)   Anzeigen Bearbeiten Löschen

Telefone
MAC-Adresse     Modell  Hot-Desk fähig     IP-Adresse
00:04:13:48:31:BB   Snom 821    Ja  10.0.0.18   Anzeigen Bearbeiten Löschen
00:04:13:48:2D:A8   Snom 821    Ja  10.0.0.11   Anzeigen Bearbeiten Löschen

User is logged in two phones? I think this should not be possible!

**Comment by spag** [comment] 2013-02-06 11:51
Which of the two log-in methods (phone menu or star code) have you used?
If only one method was used, does the problem occur when your are using the other method to log in?
Please update to the newest develop branch if possible, we have fixed some minor issues affecting phone re-sync behavior.

**Comment by duebel-** [comment] 2013-02-06 17:19
Login was done via menu. star 0 star... does not work as phone B does not have a sip account connected. I will update an come back.

**Comment by wintermeyer** [comment] 2013-02-23 12:30
Can we close this issue? Is is solved?

**Comment by spag** [comment] 2013-02-23 17:45
It could be related to issue #197

**Comment by spag** [comment] 2013-02-25 07:54
could be affected by commit 5dcdeb1c1f8c53fd80a0443d61a289e583091416

**Comment by spag** [comment] 2013-02-28 21:43
Should be fixed by now. Please feel free to reopen this ticket if the issue is still present in the newer builds.

**Closed as completed by spag** 2013-02-28 21:43 UTC
Labels: Bug
