### ISSUE TITLE
repo.amooma.de returns 404, installer fails

### ISSUE THREAD

**Issue by eimann** [amooma/GS5#273] opened 2013-03-27 11:15 UTC
After copying files, the installer will setup the package manager.
This fails due to the following misconfiguration:

```
$ curl -v http://repo.amooma.de/debian/
* About to connect() to repo.amooma.de port 80 (#0)
*   Trying 89.221.14.208... connected
> GET /debian/ HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: repo.amooma.de
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.3.7
< Date: Wed, 27 Mar 2013 11:13:51 GMT
< Content-Type: text/html
< Content-Length: 184
< Connection: keep-alive
< Location: http://amooma.de/debian/
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.3.7</center>
</body>
</html>
* Connection #0 to host repo.amooma.de left intact
* Closing connection #0
```

A client following the 301 will fail too:

```
$ curl -v http://amooma.de/debian/
* About to connect() to amooma.de port 80 (#0)
*   Trying 89.221.14.208... connected
> GET /debian/ HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: amooma.de
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx/1.3.7
< Date: Wed, 27 Mar 2013 11:14:24 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 728
< Connection: keep-alive
< Status: 404 Not Found
< X-Request-Id: e8216136d7f3583df482f113aa67787d
< X-Runtime: 0.001108
< X-Rack-Cache: miss
< 
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
</head>

<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <h1>The page you were looking for doesn't exist.</h1>
    <p>You may have mistyped the address or the page may have moved.</p>
  </div>
</body>
</html>
* Connection #0 to host amooma.de left intact
* Closing connection #0
```

The repository apparently contains the grub-install package, so it is essential to successfully finish the installation and boot into the new system.

![repo-defect](https://f.cloud.github.com/assets/2742432/307812/185742fe-96cf-11e2-9b4f-ce6255587398.png)

**Comment by eimann** [comment] 2013-03-27 11:17
Apparently this is related to issue #229

**Comment by jpawlowski** [comment] 2013-03-28 18:12
yes, thats correct. this will be fixed once the DNS setup is ready.
You may just add the following line to /etc/hosts as a temporal workaround:

`89.221.14.194 repo.amooma.de`

**Comment by jpawlowski** [comment] 2013-03-28 18:12
(closing this issue as a duplicate)

**Comment by jpawlowski** [comment] 2013-03-28 18:14
Oh and regarding normal ISO installation: You may just safely ignore the red window warning message. the install will just do fine afterwards.

**Comment by eimann** [comment] 2013-03-29 07:21
Thanks to Debian and its install process I was able to fix this issue, as ignoring the red warning dialog didn't help.
Grub was missing and therefor the install didn't boot successfully.

Here's what I did:
Change to another console, Alt+F3
chroot to /target
fix /etc/apt/sources.list with a Debian wheezy repo (main, contrib, non-free)
add the /etc/hosts entry mentioned above
run aptitude update
run aptitude install grub2
leave the chroot
choose "install grub bootloader" from the menu
be happy

Nevertheless I can't imagine why changing a DNS record takes so awfully long ... it's just an edit + waiting for it to expired from the caches.

**Comment by jpawlowski** [comment] 2013-03-29 14:40
there is a reason why it takes some more time than usual but thats all i know

**Comment by eimann** [comment] 2013-06-12 22:26
Will this ever be fixed?

**Comment by jpawlowski** [comment] 2013-06-12 22:45
I'll try to push this forward in some direction.
Root cause is still #229

**Closed as completed** 2013-06-12 22:46 UTC
Labels: wontfix
